name: backend
version: 0.1
cabal-version: >= 1.8
build-type: Simple

library
  hs-source-dirs: src
  if impl(ghcjs)
    buildable: False
  build-depends: base
               , common
               , frontend
               , obelisk-backend
               , obelisk-route
               , snap 
               , snap-core
               , io-streams 
               , bytestring
               , persistent
               , persistent-template
               , persistent-sqlite
               , time
               , transformers
               , cryptonite
               , utf8-string
               , base64-bytestring
               , memory
               , ghc
  exposed-modules:
    Backend
  other-modules:
    Routes.Login
    Routes.Posted
    Routes.Gotten
    Routes.Signup
    Database.DB
    Shared.Functions

  ghc-options: -Wall -O -fno-show-valid-hole-fits
               -- unsafe code
               -Wincomplete-record-updates -Wincomplete-uni-patterns -Wpartial-fields
               -- unneeded code
               -Widentities -Wredundant-constraints
  if impl(ghc >= 8.8)
    ghc-options:
               -Wmissing-deriving-strategies

executable backend
  main-is: main.hs
  hs-source-dirs: src-bin
  ghc-options: -Wall -O -fno-show-valid-hole-fits -threaded
               -- unsafe code
               -Wincomplete-record-updates -Wincomplete-uni-patterns -Wpartial-fields
               -- unneeded code
               -Widentities -Wredundant-constraints
  if impl(ghc >= 8.8)
    ghc-options:
               -Wmissing-deriving-strategies
  if impl(ghcjs)
    buildable: False
  build-depends: base
               , backend
               , common
               , frontend
               , obelisk-backend
               , snap 
               , snap-core
               , io-streams 
               , bytestring
               , persistent-template
               , persistent-sqlite
               , persistent
               , time
               , transformers
               , cryptonite
               , utf8-string
               , base64-bytestring
               , memory
               , ghc
